### ISSUE TITLE
confirm bibliography

### ISSUE THREAD

**Issue by ghost** [mauroporta/Autour_de_DAG#2]
Hi guys. can you confirm that the appearance of the bibliography items is ok in the version i uploaded?When I compile it comes with a strange format

**Comment by mauroporta** [comment]
This is what I get: Lee Cohn, "Differential graded categories are k-linear stable infinity categories", in: (2013).

Besides this, there is a problem with Verdier's "Des catégories abéliennes..."

If those are the problems you meant, I'll try to fix them right now!

**Comment by ghost** [comment]
No this was not the problem. But the fact that you detected these errors is a sign that there was no problem:) it is just me having problems compilling the bibliography!
Thanks! I will correct these that you mention.

**Comment by mauroporta** [comment]
No, wait! I already did that! I am pushing right now! :D

**Comment by ghost** [comment]
ok!:) thans! we can close this issue)

**Comment by mauroporta** [comment]
Perfect! :D ;) ;)
